FROM node:20-slim
WORKDIR /app
ENV NODE_ENV=development

COPY package*.json ./
RUN npm install --no-progress


RUN groupadd -r app && useradd -r -g app app
USER app
EXPOSE 3847


CMD ["npm", "run", "dev"]
